import type { Metadata } from "next";
import "./globals.css";
import Layout from "@/components/Layout";
import { geistSans, geistMono } from "@/lib/fonts";
import ThemeProvider from "@/components/ThemeProvider";
import { Toaster } from "@/components/ui/sonner";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider attribute={"class"} enableSystem defaultTheme="light">
          <Toaster/>
        <Layout>{children}</Layout>
        </ThemeProvider>
      </body>
    </html>
  );
}
